apiVersion: apps/v1beta1
kind: 
metadata:
  name: 
spec:
  selector:
    matchLabels:
      app:    
  minReadySeconds: 25
  template:
    metadata:
      labels:
        app: 
        version: 
    spec:   
      containers:
        - name: 
          image: 
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          ports:
          - containerPort: 
          imagePullPolicy: Always
          env:
           -  name:  ""
              value: ""
           -  name: ""
              value: ""