apiVersion: v1
kind: Service
metadata:
  name: mssql-svc
  labels:
    app: mssql-store
spec:
  ports:
  - protocol: TCP
    port: 
    targetPort: 
  type: LoadBalancer
  selector:
    app: mssql-store
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mssql-deploy
  labels:
    app: mssql-store
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql-store
    spec:
      containers:
      - image: 
        name: mssql-store
        ports:
        - containerPort: 
          name: sql
        env:
        - name: 
          value: 
        - name: 
          value: 
        - name: 
          value: 

        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: 
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: 