apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler 
metadata: 
  name: captureordertd 
spec: 
  minReplicas: 1 
  maxReplicas: 10 
  targetCPUUtilizationPercentage: 2
  scaleTargetRef: 
    kind: Deployment 
    name: captureordertd 
    apiVersion: apps/v1beta1 