apiVersion: v1
kind: ReplicationController
metadata:
  name: captureordertd
spec:
  replicas: 4
  selector:
    app: captureordertd
    version: v2
  template:
    metadata:
      labels:
        app: captureordertd
        version: v2
    spec:
      containers:
        - name: captureordertd
          image: shanepeckham/captureordertd:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MONGOHOST
              value: "mongodb://mongo-mongodb"