---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-db-volume-claim
  namespace: sock-shop
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: cart-db