---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cart-db-volume
  labels:
    app: cart-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: ENTER_THE_NAME_OF_YOUR_DISK_HERE
    fsType: ext4
