apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: captureordertd
spec:
  selector:
    matchLabels:
      app: captureordertd   
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: captureordertd
        version: v3
    spec:      
      containers:
        - name: captureordertd
          image: shanepeckham/captureordertd:v3
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
          env:
           -  name:  "MONGOHOST"
              value: "faldb"
           -  name: "TEAMNAME"
              value: "Tester"
