apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
  labels:
    app: mssql-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: default